name: ML-projects-torch-gpu
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab>=2.0.0
  - numpy>=1.18.1
  - bokeh>=2.0.0
  - notebook
  - ipywidgets>=7.5
  - boost-histogram
  - mplhep
  - pandas
  - opencv
  - scikit-learn
  - pytorch==1.4.0
  - torchvision
  - cudatoolkit=10.0
